### ISSUE TITLE
to_wei calculates inaccurate when value less then 1 submitted

### ISSUE THREAD

**Issue by Alegzander** [pipermerriam/ethereum-utils#17]
## What is wrong?

I've fell into issue with to_wei  when working with [web3.py](https://github.com/pipermerriam/web3.py) library and found out that it uses `eth_utils.currency.to_wei` to proceed calculation.

Short description on how I fell into issue.

I was working with smart-contract where I need to setup amount of ether it should accept to prevent cases when user submitted wrong amount.
Variable stores in wei and data is setup in constructor.

```
web3 = self.get_web3()

contract = web3.eth.contract(abi=ContractHelper.get_abi(self.CONTRACT_NAME),
                             bytecode=ContractHelper.get_bytecode(self.CONTRACT_NAME),
                             contract_name=self.CONTRACT_NAME)
...
self.transaction_id = contract.deploy(transaction={'from': AccountHelper.get_base_account(),
                             "gasPrice": web3.toWei(25, 'gwei')}, args=[web3.toWei(0.05, 'ether')])
```

For simplicity purpose I've replaced variables with raw data supply.

After deploying contract I didn't pay attention to events result until I found out that contract doesn't accept payment that was working without issue in [ethereum IDE](https://remix.ethereum.org/#version=soljson-v0.4.16+commit.d7661dd9.js)

Code seemed fine but then I've looked into events fired by contract.

![image](https://user-images.githubusercontent.com/2426298/30679397-bd0bd84c-9eb2-11e7-8798-be213e9bb41b.png)

Instead of **50000000000000000** value in wei was **50000000000000002**.

## How can it be fixed?

In general problem was with too big precision (999) that is set in default context. It goes much too deep into floating than it actually needs.

I forked repo and fixed issue. Will submit PR soon.

**Comment by carver** [comment]
For anyone looking for a workaround, you can use: `web3.toWei(str(0.05), 'ether')`

ie~ `web3.toWei('0.05', 'ether')`

**Comment by pipermerriam** [comment]
or upgrade to `ethereum-utils>=0.4.1`
