### ISSUE TITLE
Missing to_normalized_address example in README

### ISSUE THREAD

**Issue by reiven** [pipermerriam/ethereum-utils#3]
Hi!

Looks like the _to_normalized_address_ in README is merely copy of _to_checksum_address_.
It will be great to include the correct explanation and sample of it

![image](https://cloud.githubusercontent.com/assets/362717/24863273/88d60b90-1dd6-11e7-97a2-608689b48b5c.png)

**Comment by pipermerriam** [comment]
fixed via 148cb34442840f272c240c6b658845db2139b98b

Thanks for catching this.
