### ISSUE TITLE
Validating Ethereum address

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/ethereum-utils#7]
What is the best way to validate Ethereum address, assuming it might or might not be checksummed? This was not immediately clear from the APIs.

**Comment by pipermerriam** [comment]
The [`is_address`](https://github.com/pipermerriam/ethereum-utils#is_addressvalue---bool) function is the most broad.  The README covers all of the formats that it will accept.

There are 3 more functions for checking for more specific address formats.

* [`is_canonical_address`](https://github.com/pipermerriam/ethereum-utils#is_canonical_addressvalue---bool)
* [`is_checksum_address`](https://github.com/pipermerriam/ethereum-utils#is_checksum_addressvalue---bool)
* [`is_normalized_address`](https://github.com/pipermerriam/ethereum-utils#is_normalized_addressvalue---bool)

Does this answer your question?

**Comment by miohtama** [comment]
Perfect, thank you!

**Comment by miohtama** [comment]
Does this approach look sane? It's based on real world hand typed Ethereum address input data.

            # Check for any Ethereum address
            try:
                if not is_hex_address(address):
                    errors.append((csv_file, line, "Not an Ethereum address: {}".format(address)))
                    continue
            except UnicodeEncodeError:
                errors.append([csv_file, line, "Could not decode: {}".format(address)])
                continue

            # Check if checksummed address if any of the letters is upper case
            if any([c.isupper() for c in address]):
                if not is_checksum_address(address):
                    errors.append((csv_file, line, "Not a checksummed Ethereum address: {}".format(address)))
                    continue

**Comment by pipermerriam** [comment]
There's a new (`is_checksum_formatted_address`](https://github.com/pipermerriam/ethereum-utils#is_checksum_formatted_addressvalue---bool) function that you can use in place of your `c.isupper()` approach if your inclined to use it.  Otherwise, yes, this looks like the right code.
